// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Name      string             `db:"name" json:"name"`
	Password  string             `db:"password" json:"password"`
}

type Sprint struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Name             string             `db:"name" json:"name"`
	StandupStartTime pgtype.Timestamptz `db:"standup_start_time" json:"standup_start_time"`
	StandupEndTime   pgtype.Timestamptz `db:"standup_end_time" json:"standup_end_time"`
}

type Update struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	EmployeeID  pgtype.UUID        `db:"employee_id" json:"employee_id"`
	SprintID    pgtype.UUID        `db:"sprint_id" json:"sprint_id"`
	Yesterday   string             `db:"yesterday" json:"yesterday"`
	Today       string             `db:"today" json:"today"`
	BlockedBy   []string           `db:"blocked_by" json:"blocked_by"`
	Breakaway   string             `db:"breakaway" json:"breakaway"`
	CheckInTime pgtype.Timestamptz `db:"check_in_time" json:"check_in_time"`
	Status      string             `db:"status" json:"status"`
	Tasks       []string           `db:"tasks" json:"tasks"`
}
