version: '3'

services:
  
  db:
    image: "postgres"
    container_name: standup_dev_db
    restart: "always"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: standup_dev
    ports:
      - 5432:5432
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d standup_dev'" ]
      interval: 10s
      timeout: 1s
      retries: 5


  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.20.0
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=db port=5432 user=postgres password=postgres dbname=standup_dev
      - GOOSE_VERBOSE=true
      - GOOSE_COMMAND=up
    volumes:
      - ./sql/schema:/migrations