version: '3'

services:
  
  db:
    image: "postgres"
    container_name: standup_dev_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: standup_dev
    ports:
      - 5432:5432
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data

